name: CI unit tests using pytest

on:
  push:
    branches:
      - main
      - ci
  pull_request:
      branches:
        - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      run: pytest -v -rA
    - name: Test coverage report html
      run: pytest --cov-report html --cov=sisedeinversiones tests/
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: htmlcov